// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDs2droSsKEyBhKGzrkJzTxJlSo_mXwycY',
    appId: '1:267282644802:web:d74a927b18e194ac1fd2db',
    messagingSenderId: '267282644802',
    projectId: 'fir-flutter-codelab-328ca',
    authDomain: 'fir-flutter-codelab-328ca.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-328ca.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDKoOQCtue2Xr0k1R4QsCJgkGpXZjeFbo',
    appId: '1:267282644802:android:96e95149527dd4cb1fd2db',
    messagingSenderId: '267282644802',
    projectId: 'fir-flutter-codelab-328ca',
    storageBucket: 'fir-flutter-codelab-328ca.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGmSK49ZyeMjbaCynrlJUhfc_OB68Ih1c',
    appId: '1:267282644802:ios:d5858247778a94111fd2db',
    messagingSenderId: '267282644802',
    projectId: 'fir-flutter-codelab-328ca',
    storageBucket: 'fir-flutter-codelab-328ca.appspot.com',
    iosClientId: '267282644802-5f53k86a3hn6nuoaofaeo1s4u0req27u.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseGetToKnowFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGmSK49ZyeMjbaCynrlJUhfc_OB68Ih1c',
    appId: '1:267282644802:ios:d5858247778a94111fd2db',
    messagingSenderId: '267282644802',
    projectId: 'fir-flutter-codelab-328ca',
    storageBucket: 'fir-flutter-codelab-328ca.appspot.com',
    iosClientId: '267282644802-5f53k86a3hn6nuoaofaeo1s4u0req27u.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseGetToKnowFlutter',
  );
}
